//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_table
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string Department { get; set; }
        public string EmployeeName { get; set; }
        public string CompanyName { get; set; }
        public string Designation { get; set; }
    }
}
