//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task_table
    {
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Description { get; set; }
        public int Tasks { get; set; }
        public string AssignedBy { get; set; }
        public string EmployeeConfirm { get; set; }
        public string ManagerConfirm { get; set; }
    }
}
